// File: lib/firebase_options.dart
// Generated by `flutterfire configure`.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyExample-Web-Key",
    authDomain: "your-project-id.firebaseapp.com",
    projectId: "your-project-id",
    storageBucket: "your-project-id.appspot.com",
    messagingSenderId: "1234567890",
    appId: "1:1234567890:web:abcdef123456",
    measurementId: "G-ABCDEFGH",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyExample-Android-Key",
    appId: "1:1234567890:android:abcdef123456",
    messagingSenderId: "1234567890",
    projectId: "your-project-id",
    storageBucket: "your-project-id.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyExample-iOS-Key",
    appId: "1:1234567890:ios:abcdef123456",
    messagingSenderId: "1234567890",
    projectId: "your-project-id",
    storageBucket: "your-project-id.appspot.com",
    iosClientId: "1234567890-abcdefg.apps.googleusercontent.com",
    iosBundleId: "com.example.app",
  );

  static const FirebaseOptions macos = ios;

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyExample-Windows-Key",
    appId: "1:1234567890:web:abcdef987654",
    messagingSenderId: "1234567890",
    projectId: "your-project-id",
    storageBucket: "your-project-id.appspot.com",
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: "AIzaSyExample-Linux-Key",
    appId: "1:1234567890:web:abcdef987654",
    messagingSenderId: "1234567890",
    projectId: "your-project-id",
    storageBucket: "your-project-id.appspot.com",
  );
}
