// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ0VPO9SV5_c_Wrz4ENVd6mOfw9pBqlgU',
    appId: '1:1052429597413:web:e5a6748ec7de70d08bf20c',
    messagingSenderId: '1052429597413',
    projectId: 'expensetrack-30ea1',
    authDomain: 'expensetrack-30ea1.firebaseapp.com',
    storageBucket: 'expensetrack-30ea1.firebasestorage.app',
    measurementId: 'G-QRGLZTSVXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKLUfj-ha7iZsE5PTpZh9jc6VUKwkkZsg',
    appId: '1:1052429597413:android:bfffb25596be2d958bf20c',
    messagingSenderId: '1052429597413',
    projectId: 'expensetrack-30ea1',
    storageBucket: 'expensetrack-30ea1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqb8NTwjdCK7KtFX1VzJoylXQv3E-54Oc',
    appId: '1:1052429597413:ios:364bf7fbf5c9e6468bf20c',
    messagingSenderId: '1052429597413',
    projectId: 'expensetrack-30ea1',
    storageBucket: 'expensetrack-30ea1.firebasestorage.app',
    iosBundleId: 'com.example.expensetrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqb8NTwjdCK7KtFX1VzJoylXQv3E-54Oc',
    appId: '1:1052429597413:ios:364bf7fbf5c9e6468bf20c',
    messagingSenderId: '1052429597413',
    projectId: 'expensetrack-30ea1',
    storageBucket: 'expensetrack-30ea1.firebasestorage.app',
    iosBundleId: 'com.example.expensetrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfMMP7PCsJE7LQ5gGUpWM9377DLbOm1eM',
    appId: '1:1087493122048:web:437648861e4fa5a48b90e5',
    messagingSenderId: '1087493122048',
    projectId: 'expensetracker-ab893',
    authDomain: 'expensetracker-ab893.firebaseapp.com',
    storageBucket: 'expensetracker-ab893.firebasestorage.app',
    measurementId: 'G-S785MPK9VB',
  );
}